[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
label-volume =  %percentage%%
label-volume-foreground = ${root.foreground}

label-muted = 婢 0
label-muted-foreground = #666

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #f5a70a
bar-volume-foreground-4 = #f5a70a
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-foreground-7 = #ff5555
bar-volume-foreground-8 = #ff5555

bar-volume-gradient = true
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}
